# Local to found the actions - https://github.com/marketplace

name: "terraform apply"

on:
  push: 
    branches: ["main"]
    # Defines that modifications in the path terraform/ will run the Workflow
    paths: ["terraform/**"]
  # Defines that is possible to run the Workflow manually  
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials"  
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Checkout" 
        uses: actions/checkout@v4

      - name: "Terraform init" 
        working-directory: ./terraform
        run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}"
      
      - name: "Terraform Apply"
        working-directory: ./terraform
        run: terraform apply --auto-approve

